### ISSUE TITLE
Trigger bisect from GitHub comments

### ISSUE THREAD

**Issue by varkor** [rust-lang/cargo-bisect-rustc#12]
It seems like it could be possible (given the resources) to automatically bisect by mentioning a bot on an issue / PR. For example, in these recent issues: https://github.com/rust-lang/rust/issues/49706 and https://github.com/rust-lang/rust/issues/49438 the next steps are "run `cargo-bisect-rustc`. It'd be nice to do this without any intervention other than a comment.

**Comment by spastorino** [comment]
@varkor this idea would be great but at the same time is very concerning security wise and I think most of @rust-lang/infra people are against it. Mentioning them to give the final call so we can close this issue :)

**Comment by pietroalbini** [comment]
I have a few concerns about this:

* The build will have to be fully sandboxed, even if we restrict who can queue bisections. This increases the complexity and implementation time, even though [rustwide](https://github.com/rust-lang/rustwide) is probably enough.
* Deploying something using Docker containers as a sandbox (like docs.rs and Crater agents) is more complex than the other bots, as they need access to the Docker socket (which basically gives root access to the machine). A bisection bot would pose the same challenges.
* To get results in a meaningful time we can't just use the cheapest EC2 instance available. But I suspect we won't queue bisections all the time, so we'll need to justifying getting a mostly-idle instance.

The first two can be solved if someone takes the time to do that... while I have less ideas about the third issue.

**Comment by Mark-Simulacrum** [comment]
I don't think this is worth spending our time on, running bisect locally isn't actually too hard hopefully and I think improving that is a better bet.
