### ISSUE TITLE
 Option to regress based on human interaction

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo-bisect-rustc#144]
Much like #139: There are cases where the regression condition is complicated enough that someone may not want to attempt to automate it, but would *still* like to use `cargo-bisect-rustc` to handle the busy-work of downloading rust versions (especially at the commit level).

I'm thinking something like `--regress=ask`, and then after each run, the tool would just say "was that a regression [Y/N]?"

**Comment by ehuss** [comment]
Maybe I'm a bit confused, perhaps you can clarify.  There is a `--prompt` option which will interactively ask the user to determine if something is a regression or not.  Are you saying that it should also avoid running cargo and make the user run the command manually (which is more akin to `git bisect`)?  How would this be different from `--prompt`?

**Comment by pnkfelix** [comment]
Oh, maybe it *is* the same as `--prompt`, and I just overlooked that option. Closing.
