### ISSUE TITLE
Document environment variables in README or TUTORIAL

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo-bisect-rustc#182]
This was my first time using cargo-bisect-rustc and I immediately jumped to `--script` because I was looking for a codegen regression and needed to inspect the generated asm. I'm ashamed to admit how much time I wasted trying to get it to work because I spent a long time barking up the wrong tree, thinking my invocation of `cargo` in `bisect.sh` was the problem (i.e. it wasn't resolving to the version being tested) when in fact the problem was that I wasn't aware each bisection run gets its own target directory.

I found that at minimum, `CARGO_TARGET_DIR` and `CARGO_BUILD_TARGET` need to be documented front-and-center (given that the output will be stored under `$CARGO_TARGET_DIR/$CARGO_BUILD_TARGET/[release|debug]/...`.

Thanks for making this awesome tool in all cases, though!

**Comment by steffahn** [comment]
Thanks for writing this issue. I just wanted to bisect output issue, and thanks to your information here, it was really straightforward 🙂
