### ISSUE TITLE
Bisect with thread sanitizer option

### ISSUE THREAD

**Issue by Lee-Janggun** [rust-lang/cargo-bisect-rustc#204]
Is there a way to preform `cargo-bisect-rustc` with thread sanitizer enabled? I have a regression of test case that only happens with sanitizers enabled, but since `cargo-bisect-rustc` does not seem to have sanitizer options, needed to hand-bisect my case.

**Comment by ehuss** [comment]
You should be able to use `RUSTFLAGS="-Zsanitizer=thread"` like you would normally. If your use case needs `build-std`, then you'll also need to pass `-c rust-src` to download the std source. 

Can you say more if that doesn't help?

**Comment by Lee-Janggun** [comment]
I was missing the build-std option. Thank you very much!
