### ISSUE TITLE
Structured documentation and examples

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo-bisect-rustc#264]
@oli-obk Would you be ok with me moving the cargo-bisect-rustc documentation into an mdbook published on GitHub Pages? I'd like to organize the documentation better. And more importantly I want to collect a variety of recipes (examples) of how to do various things. For example, I often forget how to do more complex tasks on Windows, and having something I could just copy/paste would save a lot of time.

**Comment by oli-obk** [comment]
That sounds great!
