### ISSUE TITLE
feature request: Invert status

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo-bisect-rustc#28]
Add ability to look for any change in success status. i.e. not only went from good to bad, but also from bad to good.

**Comment by Mark-Simulacrum** [comment]
If I understand you correctly, I think this would probably require something more interesting than a binary search - we need the status to be monotonic (i.e. change only once). Perhaps I'm misunderstanding you though? We certainly can naively see if the status has changed under us and warn/print that...

**Comment by nagisa** [comment]
Status changing only once is fine, its just that currently cargo-bisect-rustc requires the start end to always succeed and the end end to always fail.

**Comment by nagisa** [comment]
Basically my goal today was to see where a bug was fixed, rather than appeared :)

**Comment by Mark-Simulacrum** [comment]
I think I'd be happy to accept a PR for this change.. not sure I'll get a chance myself in the next few days.

**Comment by spastorino** [comment]
@nagisa I know this is a bit old, trying to get this repo in shape a but. Is @kennytm suggestion enough? or are you up to provide a PR with your idea?

**Comment by nagisa** [comment]
Using a script worked for me and I used the trick more than once since. I think this is a common enough want to implement it in bisect-rustc but I also don't think it is super critical.
