### ISSUE TITLE
Panics with "~" in test-dir

### ISSUE THREAD

**Issue by LegNeato** [rust-lang/cargo-bisect-rustc#29]
`--test-dir=$HOME/test/crate` works, `--test-dir=~/test/crate` panics:
```
thread 'main' panicked at 'failed to run "cargo" "+bisector-nightly-2019-01-01-x86_64-apple-darwin" "build": Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:538:17
```

**Comment by ehuss** [comment]
Tilde expansion is done by the shell (assuming you are using bash or something sh-like).  Use a space instead of `=` to separate the arguments, like `--test-dir ~/test/crate`.

**Comment by spastorino** [comment]
I think this is resolved with what @ehuss suggested. Feel free to comment again if you consider that something should be addressed.
