### ISSUE TITLE
Add custom "Satisfies" terms

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo-bisect-rustc#316]
## Request
Add `--term-old` and `--term-new` CLI options to customize the "Satisfies" terms.

## Problem
Currently, cargo-bisect-rustc prints "Yes" or "No" (or new terms of #311) on whether or not a build satisfies the condition that it is looking for. However, this terminology is either confusing or backwards depending on what you are testing. 

For example, you can use one of `--regress` options to find when a regression was *fixed*. In that sense, the "old" is "regression found" and the "new" is "regression fixed", which is backwards from the normal behavior.

## Proposal
Taking inspiration from `git bisect`, I think it would be good to have custom terms for `Satisfies`. I think adding cli options like `--term-old="compiled successfully"` and `--term-new="failed to compile"` would allow the user to specify their own wording. Then, the `--regress` option could set the defaults for those terms appropriate for the regression type.

**Comment by apiraino** [comment]
@rustbot claim

I'm working on a patch
