### ISSUE TITLE
error: unknown crate type: `proc-macro`

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/cargo-bisect-rustc#32]
On a trivial project created by ```cargo new``` (and removing the `edition` from `Cargo.toml`):

```
$ cargo bisect-rustc --start 2016-06-16 --end 2016-10-03 --prompt
checking nightly-2016-06-16
std for x86_64-unknown-linux-gnu: 58.89 MB / 58.89 MB [=======================================================================================] 100.00 % 11.15 MB/s
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 101)
--- stderr
error: unknown crate type: `proc-macro`



nightly-2016-06-16 finished with exit code Some(101).
please select an action to take:
uninstalling nightly-2016-06-16
the --start nightly has the regression
```

**Comment by Mark-Simulacrum** [comment]
Bisecting into 2016 with a recent Cargo and without the `--with-cargo` option is highly unlikely to work. I think this should work if you pass `--with-cargo` though -- let me know if not and we can reopen!

**Comment by ExpHP** [comment]
It does not work with `--with-cargo` either:

```
$ cargo bisect-rustc --start 2016-06-16 --end 2016-10-03 --with-cargo
checking nightly-2016-06-16
std for x86_64-unknown-linux-gnu: 58.89 MB / 58.89 MB [=========================] 100.00 % 11.06 MB/s  uninstalling nightly-2016-06-16
Could not download toolchain: Tarball not found at https://static.rust-lang.org/dist/2016-06-16/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
```

**Comment by Mark-Simulacrum** [comment]
Looks like we don't support dates that far back -- the Cargo binaries were kept in a different directory (e.g., in this case it'd be in https://static.rust-lang.org/cargo-dist/2016-06-16/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz). You could probably download that manually and put it in the path before calling and that *should* work.

**Comment by ExpHP** [comment]
Thanks!  However, I'm not sure where it wants the file to be placed.

(also, will it only need the one, or will it need it for all commits it tries to visit? If it's the latter, I might just be better off installing toolchains through rustup to bisect for now...)

**Comment by Mark-Simulacrum** [comment]
Should most likely just be the one. You can place it anywhere -- I was suggesting unpacking that tarball and then doing something like `PATH=/path/to/tarball/bin/dir:$PATH ./target/release/bisect...`

**Comment by ExpHP** [comment]
Oh, duh!  I see what you mean now.  (run it *without* `--with-cargo` :stuck_out_tongue:)

It appears this version predates `cargo check` as well, but that can be worked around with `--script`.

**script**
```
#!/usr/bin/env bash
cargo build
```

```
$ PATH=$(pwd)/cargo-nightly-x86_64-unknown-linux-gnu/cargo/bin:$PATH ~/.cargo/bin/cargo-bisect-rustc --start 2016-06-16 --end 2016-10-03 --script ./script
```
Seems to be running well now!

**Comment by spastorino** [comment]
I wonder if we should keep this issue open.

**Comment by Mark-Simulacrum** [comment]
Skimming, yes, looks like we can close.
