### ISSUE TITLE
Rename/Add new github token env var

### ISSUE THREAD

**Issue by apiraino** [rust-lang/cargo-bisect-rustc#331]
For consistency with the [triagebot](https://github.com/rust-lang/triagebot/blob/1cf4cebbf0f662dade4f596125ee7ec365e93b73/src/github.rs#L1985), I'd like this tool to use `GITHUB_API_TOKEN` as env var to pick up the github API token.

So basically renaming all occurrences of `GITHUB_TOKEN` to `GITHUB_API_TOKEN`.

Or viceversa. Right now I have two env vars for the same job 

If we don't want to break anyone's workflow, I'm ok with just also adding the new one :^)

(opening this issue as self-reminder to do that, cannot self-assign on this repo)

**Comment by Mark-Simulacrum** [comment]
Can we instead move triagebot rather than this repo? I feel like GITHUB_TOKEN is sort of more standard, e.g. https://docs.github.com/en/actions/security-guides/automatic-token-authentication and triagebot is likely less used.
