### ISSUE TITLE
Using the Github API instead of a local git repository

### ISSUE THREAD

**Issue by hellow554** [rust-lang/cargo-bisect-rustc#40]
If you want to use this tool you either specify a local git repository **at compile time** or it will always clone a bare repository on every `cargo-bisect-rustc` run. 

This is somewhat inconvenient and using the Github API is something one could do instead.

What are your thoughts about it? I'd like to implement it, maybe as a flag (`--no-local-git-repo-is-available-so-use-github-instead-plz`)

**Comment by Mark-Simulacrum** [comment]
If we can reliably use the GitHub API (without, e.g., hitting rate limits) then I would love to do that by default (with perhaps a flag to fallback to local git repo). Happy to accept a PR!

**Comment by spastorino** [comment]
:+1: to this idea too.

**Comment by pnkfelix** [comment]
I have a [prototype](https://github.com/pnkfelix/cargo-bisect-rustc/tree/use-github-api) of this that I need to rebase.
