### ISSUE TITLE
Downloaded toolchains do not support components

### ISSUE THREAD

**Issue by cr1901** [rust-lang/cargo-bisect-rustc#43]
## Scope
I'm trying to use `cargo-bisect-rustc` to find when a size regression for the `msp430` target was introduced. Right now, `msp430` requires [`xargo`](https://github.com/japaric/xargo) to build, which is essentially a small wrapper over cargo that compiles libcore on-the-fly while `msp430`'s libcore isn't built as part of CI.

`xargo` itself requires that the `rustup` component `rust-src` is available. However, when I attempt to run `cargo-bisect-rustc` against a [sample repo](https://github.com/cr1901/msp430-size) with the regression, the script I provide always fails with `error: toolchain 'bisector-nightly-2019-03-27-x86_64-unknown-linux-gnu' does not support components`.

The `bisector-` prefix appears to be [deliberate](https://github.com/rust-lang/cargo-bisect-rustc/blob/master/src/main.rs#L263-L266). However, I can't obtain the `rust-src` corresponding to each nightly thanks to the prefix. Therefore, I can't use this tool to bisect and look for when the size regression was introduced.

What options do I have?

### `test.sh`
```
#!/bin/sh
NOBM_FILE=`mktemp`
BM_FILE=`mktemp`

rustup component add rust-src

xargo build --manifest-path=take-api/Cargo.toml --release --target=msp430-none-elf --example min --features bare_metal
msp430-elf-size -A target/msp430-none-elf/release/examples/min > $BM_FILE

xargo build --manifest-path=take-api/Cargo.toml --release --target=msp430-none-elf --example min
msp430-elf-size -A target/msp430-none-elf/release/examples/min > $NOBM_FILE

diff -u $NOBM_FILE $BM_FILE

rm $NOBM_FILE $BM_FILE
```

```
william@xubuntu-dtrain:~/Projects/msp430-size$ cargo-bisect-rustc --script=./test.sh --preserve-target --preserve --start=2019-03-27 --end=2019-09-04 --prompt
checking nightly-2019-03-27
error: toolchain 'bisector-nightly-2019-03-27-x86_64-unknown-linux-gnu' does not support components
error: caused by: invalid toolchain name: 'bisector-nightly-2019-03-27-x86_64-unknown-linux-gnu'
error: `rust-src` component not found. Run `rustup component add rust-src`.
note: run with `RUST_BACKTRACE=1` for a backtrace
error: `rust-src` component not found. Run `rustup component add rust-src`.
note: run with `RUST_BACKTRACE=1` for a backtrace


nightly-2019-03-27 finished with exit code Some(0).
please select an action to take:
> mark regressed
  mark baseline
  retry
```

**Comment by ehuss** [comment]
Have you tried the `--with-src` option?

**Comment by cr1901** [comment]
Somehow I managed to miss that option. I was able to find the regressed commit with the following command line: `cargo-bisect-rustc --script=./test.sh --preserve-target --preserve --start=2019-03-27 --end=2019-09-04 --with-src --with-cargo`

Closing due to user error :P.
