### ISSUE TITLE
Bisect rollups

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo-bisect-rustc#44]
Is it possible it could figure out which PR in a roll-up was responsible? 
That really would be the ICEing on the cake.

**Comment by ehuss** [comment]
I don't think it is possible with `cargo-bisect-rustc`, since individual artifacts are not saved.  Usually you can just look at the list of PRs and make an educated guess.  You can use `git bisect` if you really don't know which commit is responsible, but that would probably take hours to run.

**Comment by gilescope** [comment]
Fair enough.
