### ISSUE TITLE
Cargo emits "error: Unrecognized option: 'json'" error beginning ~ 07/2019, consider option to bisect rustc directly without Cargo

### ISSUE THREAD

**Issue by chrissimpkins** [rust-lang/cargo-bisect-rustc#49]
From the conversation of a `cargo-bisect-rustc` ICE analysis in https://github.com/rust-lang/rust/issues/69096#issuecomment-585880012 where the error message `error: Unrecognized option: 'json'` occurred as of the 2019-07-30 nightly.

@eddyb said:

> That suggests that you're using a Cargo too new or somehow back-compat logic was removed (or never present?) in Cargo (not sure what our policy is).
>
>You need an older Cargo to go back past the addition of --json.
>
>But also it would be nice if Cargo didn't need to be involved in the bisection process, because it IMO unnecessarily complicates it.

```
cargo 1.41.0 (626f0f40e 2019-12-03)
release: 1.41.0
commit-hash: 626f0f40efd32e6b3dbade50cd53fdfaa08446ba
commit-date: 2019-12-03
```

```
cargo 1.43.0-nightly (3c53211c3 2020-02-07)
release: 1.43.0
commit-hash: 3c53211c3d7fee4f430f170115af5baad17a3da9
commit-date: 2020-02-07
```

**Comment by eddyb** [comment]
Specifically in this case, the testcase is just one file and should reproduce with just `rustc`, I think we should have *the option* to bisect `rustc` directly without Cargo.

**Comment by lqd** [comment]
You don't have to use cargo: you can bisect using the `--script` flag to point at a custom script triggering the behaviour you need, e.g. calling `rustc` directly.

**Comment by chrissimpkins** [comment]
I opened #47 with a few script extensions and it sounds like the consensus is that much of this functionality belongs in the tool rather than as extensions through scripts.  I can close this if it seems like an appropriate area for scripting.
