### ISSUE TITLE
Mention `--with-cargo` in tutorial or make it a default

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/cargo-bisect-rustc#81]
Without correct version of cargo any version of rustc that is older than few weeks will produce  random build errors which will be counted as "regression found" by default.

It is pretty confusing when `bisect-rustc` tells that revision `xyz` produces an error and silently stops bisecting correctly, while `cargo +xyz build` doesn't produce any error when run explicitly.

**Comment by chrissimpkins** [comment]
For my reference:

configuration source is here:

https://github.com/rust-lang/cargo-bisect-rustc/blob/82e234fb0784ad14f419aed05f33a9fa7c3ca4fe/src/main.rs#L96-L100

https://github.com/rust-lang/cargo-bisect-rustc/blob/6baf139e30cef747c1ebf69e583972b6ac72fa88/src/toolchains.rs#L430-L440

install source is here:

https://github.com/rust-lang/cargo-bisect-rustc/blob/6baf139e30cef747c1ebf69e583972b6ac72fa88/src/toolchains.rs#L234-L244

**Comment by chrissimpkins** [comment]
#98
