### ISSUE TITLE
Searched date range misreported

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo-bisect-rustc#82]
https://github.com/bjorn3/cargo-bisect-rustc-bot-jobs/runs/650650115#step:6:107

I told cargo bisect-rustc to bisect up to 2020-04-25 and it did that, but in the final report it said that it bisected up to 2020-04-10

**Comment by spastorino** [comment]
My guess is that this is because our jumps are not considering the start date, If that's the case when that happens we should just adjust the date to use the provided one.

**Comment by chrissimpkins** [comment]
Fixed in v0.5.0 and now available on crates.io.  Thanks for reporting this!

**Comment by bjorn3** [comment]
Updated cargo-bisect-rustc-bot.
