### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo-bisect-rustc#84]
To bisect hangs.

**Comment by Mark-Simulacrum** [comment]
Timeout to what? What hangs? Can you provide more clarification?

**Comment by bjorn3** [comment]
If the rustc regression is a hang, it would be useful for cargo-bisect-rustc to timeout after testing for a certain amount of time and then considering that timeout as if the compiler crashed.

**Comment by bjorn3** [comment]
For context: I was trying to bisect https://github.com/rust-lang/rust/issues/72051.

**Comment by hkratz** [comment]
Quite a few "extreme" slowness / hang issues lately where that would help do an unattended bisect instead of using `--prompt`.

**Comment by ehuss** [comment]
This is now implemented via #135 and should be in the recently published 0.6.1.  Feel free to open new issues if there are any problems with the new `--timeout` option.
